---
 - hosts: all
   name: Install and configure apache
   vars:
     jdk_archive: jdk-8u131-linux-x64.tar.gz
     local_source: /software/"{{jdk_archive}}"
     local_source2: /software/jdk-8u131-linux-x64.tar.gz
     local_source3: /software/jdk.tar.gz

   tasks:
   - name: check if file source exists
     stat:
       path: "{{ local_source }}"
   - name: check if file source exists
     stat:
       path: "{{ local_source2 }}"
   - name: check if file source exists
     stat:
       path: "{{ local_source3 }}"
