---
- hosts: all
  #remote_user: ansible
  #sudo: yes
  #become: true
  vars:
  tasks:
    - name: Disable selinux
      selinux:
        state: disabled
    - name: be sure firewalld is disabled
      systemd:
        name: firewalld
        enabled: no
    - name: be sure firewalld is stopped
      systemd:
        name: firewalld
        state: stopped
