---
- hosts: all
  #remote_user: ansible
  #sudo: yes
  #become: true
  vars:
    wildfly_archive: wildfly-14.0.1.Final.tar.gz
    wildfly_local_dir: wildfly-14.0.1.Final
    target_folder: /app
    wildfly_path: "{{ target_folder }}/{{ wildfly_local_dir }}"
    local_source: /software/{{ wildfly_archive }}
    slink_path: "{{ target_folder }}/wildfly"

  tasks:
  - name: Create Directory structure
    file: path="{{ target_folder }}" state=directory
    file: path="{{ wildfly_path }}" state=directory

  - name: Unpack archive
    unarchive:
     src: "{{ local_source }}"
     dest: "{{ target_folder }}"

  - name: Fix ownership
    file: state=directory path="{{ target_folder }}" owner=wildfly group=wildfly recurse=yes

  - name: Create symbolic links
    file:
      src: "{{ wildfly_path }}"
      dest: "{{ slink_path }}"
      state: link

  - name: Create admin user for wildfly admin console
    shell: "java -version"
# {{ slink_path }}/bin/add-user.sh -s admin password"
    ignore_errors: true
