---
- hosts: all
  #remote_user: ansible
  #sudo: yes
  #become: true
  vars:
    jdk_archive: jdk-8u131-linux-x64.tar.gz
    jdk_local_dir: jdk1.8.0_131
    download_folder: /java
    slink_path: /opt/java
    profile_path: /etc/profile
    java_name: "{{ download_folder }}/{{ jdk_local_dir }}"
    local_source: /software/{{jdk_archive}}

  tasks:
  - name: Create Directory structure
    file: path="{{download_folder}}" state=directory
    file: path="{{java_name}}" state=directory

  - name: Unpack archive
    unarchive:
     src: "{{ local_source }}"
     dest: "{{ download_folder }}"

  - name: Fix ownership
    file: state=directory path="{{ download_folder }}" owner=root group=root recurse=yes

  - name: Create symbolic links
    file:
      src: "{{ java_name }}"
      dest: "{{ slink_path }}"
      state: link

  - name: put JDK_HOME in /etc/profile
    lineinfile:
      path: "{{ profile_path }}"
      line: 'export JDK_HOME="{{ slink_path }}"'

  - name: put JAVA_HOME in /etc/profile
    lineinfile:
      path: "{{ profile_path }}"
      line: 'export JAVA_HOME="{{ slink_path }}"'

  - name: put JRE_HOME in /etc/profile
    lineinfile:
      path: "{{ profile_path }}"
      line: 'export JRE_HOME="{{ slink_path }}"/jre'

  - name: put JAVA bin in /etc/profile
    lineinfile:
      path: "{{ profile_path }}"
      line: 'export PATH=$PATH:"{{ slink_path }}"/bin:"{{ slink_path }}"/jre/bin'
