- name: Deploy war
  hosts: all
  tasks:
    - name: Deploy war from src to dest
      copy:
        src: /ansible/templates/sample.war
        dest: /app/wildfly/standalone/deployments/sample.war
        mode: 0750
        owner: wildfly
        group: wildfly
