---
 - hosts: all
   name: upload standalone config
   vars:
   handlers:
    - name: start wildfly
      shell: 'source /etc/profile; nohup /app/wildfly/bin/standalone.sh 2>&1 &'
      listen: "start wildfly"

   tasks:
    - name: Update standalone.xml config
      template:
         src: /ansible/templates/standalone.xml.j2
         dest: /app/wildfly/standalone/configuration/standalone.xml
         backup: yes

    - name: Start wildfly
      command: echo "this task will start wildfly"
      notify: "start wildfly"

#    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
