---
 - hosts: all
   name: upload standalone config
   vars:
   handlers:

   tasks:
    - name: Update standalone.xml config
      copy:
         src: /ansible/templates/standalone.xml.j2
         dest: /app/wildfly/standalone/configuration/standalone.xml
         backup: yes

    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
