- name: Poweron vm
  hosts: all
  connection: local
  vars:
    vm_name: ICOINFAPN084_redhat
    vm_folder: ICO/Non-Production
    vm_datacenter: ICO

  tasks:
    - name: power on vm
      vmware_guest:
        name: "{{ vm_name }}"
        state: poweredoon
