- name: Change Password
  hosts: all
  connection: local
  vars:
    vm_name: ICOINFAPN084_redhat
    vm_folder: ICO/Non-Production
    vm_datacenter: ICO
    vm_snapshot_name: clean

  tasks:
    - name: revert a snapshot
      vmware_guest_snapshot:
        name: "{{ vm_name }}"
        folder: "{{ vm_folder }}"
        datacenter: "{{ vm_datacenter }}"
        state: revert
        snapshot_name: "{{ vm_snapshot_name }}"

    - name: power on vm
      vmware_guest:
        name: "{{ vm_name }}"
        state: poweredon
