- name: Change Password
  hosts: all
  connection: local
  tasks:
    - name: revert a snapshot
      vmware_guest_snapshot:
           name: ICOINFAPN085_redhat
           datacenter: ICO
           state: revert
           snapshot_name: clean
