- name: Change Password
  hosts: all
  connection: local
  tasks:
    - name: revert a snapshot
      vmware_guest_snapshot:
#        hostname: 192.168.3.36
        name: ICOINFAPN085_redhat
#        folder: ICO/Non-Production
        datacenter: ICO
        state: revert
        snapshot_name: clean

    - name: power on vm
      vmware_guest:
        name: ICOINFAPN085_redhat
#        folder: ICO/Non-Production
        state: poweredon
